### PR TITLE
Do not crash when git repo has no commits yet

### LINKED ISSUE #258: Adding a git remote with no commits causes an error
And the user has no way to clear the cache to get back out of it.

### PR DESCRIPTION
**Pull request by singpolyma**
Closes #258

### CODE REVIEW

File: app/site.rb [hunk 1]
```diff
@@ -117,6 +117,12 @@ def git?
 			cache_path.join('.git').directory?
 		end
 
+		def log
+			git.log.tap(&:size)
```
Comment (ericroberts) [inline app/site.rb]: What is `git.log` when there are no entries? If it's nil we could return `Array(git.log)`.

File: app/site.rb [hunk 2]
```diff
@@ -217,21 +223,31 @@ def makefile?
...
-			git.status.each do |f|
-				if f.type
-					if user && user.email
-						git.commit("#{message} via tint", author: "#{user.fn} <#{user.email}>")
-					else
-						git.commit("#{message} via tint")
-					end
+			begin
+				status = git.status
+			rescue Git::GitExecuteError
```
Comment (ericroberts) [inline app/site.rb]: So status fails if there are no commits, then we rescue and just commit since there is nothing to loop over? Am I understanding that correctly?

File: app/site.rb (hunk 1 above)
Comment (singpolyma) [inline app/site.rb]: `git.log` is always an abstraction around the idea of the "git log".  It is lazy, so just asking for the log does not actually even check to see if there is a git repo at all.  That is why I have to ask it for something (like the elements, or here the size) in order to force it to look in the repo and thus throw the exception if things go poorly.

File: app/site.rb (hunk 2 above)
Comment (singpolyma) [inline app/site.rb]: Yes, if there are no commits status will fail, so we know we can't be doing an empty commit attempt (since we added something that cannot have already been there -- nothing was there) so we just make the commit.
