### PR TITLE
YML editing bugs

### LINKED ISSUE #175: no implicit conversion of Fixnum into String
When trying to edit a .tint.yml file with the following contents, we get a TypeError exception.

``` yml
options:
  colours:
    red: Rouge
    blue: Bleu
    white: Blanc
  numbers:
    - 0
    - 1
    - 2
    - 3
    - 10
  pastas:
    spa: Spaghetti
    pen: Penne
    rot: Rotini
    bar: Barbina
    cap: Capellini
    fus: Fusilli
```

### PR DESCRIPTION
**Pull request by ericroberts**
Fixes #175

### CODE REVIEW

File: app/form_helpers.rb [hunk 1]
```diff
@@ -78,7 +78,7 @@ def convert_dates
 				merge(self) do |k,v|
 					v = Date.parse(v) if is_date?(k, v)
 					FormHelpers.process(v, dir)
-				end
+				end.to_h
```
Comment (singpolyma) [inline app/form_helpers.rb]: test it

File: app/views/inputs/multipleselect.slim [hunk 2]
```diff
@@ -1,4 +1,4 @@
 input type="hidden" name="#{name}[]"
 select name="#{name}[]" multiple="multiple"
 	- options.each do |ovalue, display|
-		option value=ovalue selected=("selected" if value.to_s.include?(ovalue)) = display
+		option value=ovalue selected=("selected" if value.map(&:to_s).include?(ovalue.to_s)) = display
```
Comment (ericroberts) [inline app/views/inputs/multipleselect.slim]: I'm going to refactor this to pass in the options with selected already set, that way I can more easily test it.

**Comment by ericroberts** [comment]
@singpolyma tested
